/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othello.ui;

import com.othello.entities.Case;
import com.othello.entities.CaseValue;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author macbookpro
 */
public class BoardPanel extends javax.swing.JPanel {
    
    
    public Case[][] board;
    public CaseValue turn;

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel(Case[][] board) {
        this.board = board;
        initComponents();
        addMouseListener(new MouseAdapter() {
                @Override
                public void mouseReleased(MouseEvent e) {
                    int j = e.getX() / getCaseWidth();
                    int i = e.getY() / getCaseHeight();
                    board[i][j].setValue(turn);
                    turn = turn == CaseValue.BLACK ? CaseValue.WHITE : CaseValue.BLACK;
                    calculatePossibleMoves();
                    repaint();
                }
            });
    }
    
    @Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);
        doDrawing(g);
    }
    
    private void doDrawing(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        
        // draw the green bg
        g2d.setColor(new Color(32,144,103));
        g2d.fillRect(0, 0, getWidth(), getHeight());
        
        // draw the cases
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                int x = j * getCaseWidth();
                int y  = i * getCaseHeight();
                g2d.setColor(Color.black);
                g2d.drawRect(x,y, getCaseWidth(), getCaseHeight());
                if(board[i][j].getValue() == CaseValue.EMPTY) {
                    if(board[i][j].isPossibleMove())
                        g2d.drawOval(x + 10, y + 10, getCaseWidth() - 20, getCaseHeight() - 20);
                    continue;
                }
                
                g2d.setColor(board[i][j].getValue() == CaseValue.BLACK ? Color.black : Color.white);
                g2d.fillOval(x + 10, y + 10, getCaseWidth() - 20, getCaseHeight() - 20);
            }
        }
    }
    
    public int getCaseWidth(){
        return getWidth() / 8;
    }
    
    public int getCaseHeight(){
        return getHeight() / 8;
    }
    
    public void calculatePossibleMoves(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
